
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#ifndef _FISH_
#define _FISH_

void clearScreen();
int _putchar(char c);
void _puts(char *s);
void start();
void fish1();
void fish2();
void fish3();
void fish4();
void fish5();
void fish6();
void fish7();
void fish8();
void fish9();
void fish10();
void fish11();
void fish12();
void fish13();
void fish14();
void fish15();
void fish16();
void fish17();
void fish18();
void fish19();
void fish20();
void fish21();
void fish22();
void fish23();
void fish24();
void fish25();
void fish26();
void fish27();
void fish28();
void fish29();
void fish30();
void fish31();
void fish32();
void fish33();
void fish34();
void fish35();
void fish36();
void fish37();
void fish38();
void fish39();
void fish40();
void fish41();
void fish42();
void fish43();
void fish44();
void fish45();
void fish46();
void fish47();
void fish48();
void fish49();
void fish50();
void fish51();
void fish52();
void fish53();
void fish54();
void fish55();
void fish56();
void fish57();
void fish58();
void fish59();
void fish60();
void fish61();
void fish62();
void fish63();
void fish64();
void fish65();
void fishfin();
void fishcredfish();
void fishcredman();
void fishcredXtra();
void thanks();
#endif
